### ISSUE TITLE
Slow insert operations by historymanager (temporal representation of entities)

### ISSUE THREAD

**Issue by joriwinderickx-fm** [ScorpioBroker/ScorpioBroker#223]
We are evaluating the use of the temporal interface of NGSI-LD using Scorpio in high data rate scenarios. Our data flow consists of sending batches of data to the temporal interface and polling the interface at a certain interval to retrieve the latest known values of a certain entity/attribute.

Example transmit script:

```sh
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/temporal/entities/' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
        "id": "urn:entities:E00001", 
        "type": "E",
        "A00": [
            { 
                "type": "Property", 
                "value": "biwthuIWIDGv",
                "observedAt" : "2021-02-23T01:07:37.000Z"
            },
            { 
                "type": "Property", 
                "value": "ciwthuIWIDGv",
                "observedAt" : "2021-02-23T01:07:38.000Z"
            },
            { 
                "type": "Property", 
                "value": "diwthuIWIDGv",
                "observedAt" : "2021-02-23T01:07:39.000Z"
            }
        ],
        "@context": [
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
        ]
    }'
```

Example receive script:

```sh
curl --location --request GET 'http://localhost:9090/ngsi-ld/v1/temporal/entities/urn:entities:E00001?timerel=after&time=2021-02-23T01:07:39.000Z'
```

Docker compose setup:

```yaml
version: '3'

services:

  zookeeper:
    image: zookeeper
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_latest
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres
```

We developed some custom scripts to check how fast this data flow could be in terms of throughput and latency. We noticed that Scorpio can ingest quite easily a lot of data, but, it seems it is only slowly being ingested internally by the PostgreSQL database. It results in a low throughput and high latency (buffer build up) at the receiving end. Is it possible that these temporal values are inserted row-by-row and not in bulk?
If bulk insert is not yet used, I think it could greatly speed up the ingest performance of the temporal interface. If it is used, do you have some ideas on how to improve the ingest performance?
