### ISSUE TITLE
QoS for notifications in a replicated deployment

### ISSUE THREAD

**Issue by Blobonat** [ScorpioBroker/ScorpioBroker#331]
I'm trying to scale Scorpio horizontally using Kubernetes with the `scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.20` image. 
In my test setup I create 1 subscription and monitor the notifications. With 1 replica everything works as expected. When using multiple replicas running against the same Kafka and Postgres, I noticed that more notifcations are sent than expected. Is there any "QoS" for event/subscription processing supported by Scorpio AAIO like at least once/at most once/exactly once? 

Entity updates are sent to Scorpio via a ClusterIP service. Below is my k8s deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scorpio
  name: scorpio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scorpio
  template:
    metadata:
      labels:
        app: scorpio
      containers:
      - image: "scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.20"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9090
        env:
        - name: BOOTSTRAP_SERVERS
          value: <External Kafka>
        - name: DBHOST
          value: <External Postgres>
        - name: DBPORT
          value: 5432
        - name: DBUSER
          value: ngb
        - name: DBPASS
          value: ngb123456
        - name: DBNAME
          value: ngb
      restartPolicy: Always
```
