### ISSUE TITLE
Subscription/Notification problems when using the entityOperations endpoint

### ISSUE THREAD

**Issue by Blobonat** [ScorpioBroker/ScorpioBroker#337]
Hi,

I was playing around with the subscription options and noticed several bugs (?) within Scorpios notification behavior when using the `entityOperations` endpoint to create/update entities:
- Subscription with `attributes` does not include these attributes in the notification, when entity was created using the `entityOperations/create` endpoint
- Subscription without `attributes` does not include all attributes in the notification, when entity was created using the `entityOperations/create` endpoint

**Tested version:** scorpiobroker/all-in-one-runner:spring-kafka-latest with state of 2022-10-09 (I also tested scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.22 and noticed the same behavior)

Docker-Compose:
```
version: "3.8"
services:
  # Scorpio Context Broker
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181"

  kafka:
    image: bitnami/kafka:3.2.3
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  scorpio:
    image: scorpiobroker/all-in-one-runner:spring-kafka-latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - kafka
```

When creating subscriptions for entities that were created via the `entityOperations/create` the notification seems to be broken.

- Initially I create the following entity using the `entityOperations/create` endpoint:
```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/entityOperations/create' \
--header 'Content-Type: application/json' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '[
    {
        "id": "urn:ngsi-ld:Vehicle:A100",
        "type": "Vehicle",
        "brandName": {
            "type": "Property",
            "value": "Mercedes"
        },
        "speed": {
            "type": "Property",
            "value": 80
        }
    }
]'
```
- I update the `speed` property (tested with `entityOperations/upsert/` and direct attribute update)
```
curl --location --request PATCH 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Vehicle:A100/attrs/speed' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "Property",
    "value": 80
}'
```
```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/entityOperations/upsert/' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "id": "urn:ngsi-ld:Vehicle:A100",
        "type": "Vehicle",
        "speed": {
            "type": "Property",
            "value": 80
        }
    }
]'
```

**Subscription with attributes does not include these attributes in the notification**

- Created subscription:
```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/json' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
  "id": "urn:ngsi-ld:Subscription:withAttributes",
  "type": "Subscription",
  "entities": [{"type": "Vehicle"}],
  "watchedAttributes": ["speed"],
  "throttling": 0,
  "notification": {
    "format": "normalized",
    "attributes": ["speed", "brandName"],
    "endpoint": {
      "uri": "https://webhook.site/b8930c94-f365-4670-8c6c-467041f27356",
      "accept": "application/ld+json"
    }
  }
}'
```
- Expected behavior: Whenever `speed` property is updated, the notification includes `speed` and `brandName`
- Actual behavior: Notification only includes `speed`
```
{
  "id": "ngsildbroker:notification:-5975684014725996323",
  "type": "Notification",
  "subscriptionId": "urn:ngsi-ld:Subscription:withAttributes",
  "notifiedAt": "2022-10-09T19:38:56.662000Z",
  "data": [
    {
      "id": "urn:ngsi-ld:Vehicle:A100",
      "type": "Vehicle",
      "speed": {
        "type": "Property",
        "value": 80
      },
      "@context": [
        "https://fiware.github.io/data-models/full-context.jsonld"
      ]
    }
  ]
}
```

**Subscription without `attributes` does not include all attributes in the notification**
- Created subscription:
```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/json' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
  "id": "urn:ngsi-ld:Subscription:withoutAttributes",
  "type": "Subscription",
  "entities": [{"type": "Vehicle"}],
  "watchedAttributes": ["speed"],
  "throttling": 0,
  "notification": {
    "format": "normalized",
    "endpoint": {
      "uri": "https://webhook.site/b8930c94-f365-4670-8c6c-467041f27356",
      "accept": "application/ld+json"
    }
  }
}'
```
- Expected behavior: Notification includes all properties of vehicle
- Actual behavior: Notification does not include `brandName`, but `createdAt` and `modifiedAt`
```
{
  "id": "ngsildbroker:notification:-5040303980358933300",
  "type": "Notification",
  "subscriptionId": "urn:ngsi-ld:Subscription:withoutAttributes",
  "notifiedAt": "2022-10-09T19:38:56.662000Z",
  "data": [
    {
      "id": "urn:ngsi-ld:Vehicle:A100",
      "type": "Vehicle",
      "createdAt": "2022-10-09T19:38:15Z",
      "modifiedAt": "2022-10-09T19:38:15Z",
      "speed": {
        "type": "Property",
        "value": 80
      },
      "@context": [
        "https://fiware.github.io/data-models/full-context.jsonld"
      ]
    }
  ]
}
```

---

When creating the entity via the `entities` endpoint the notification behavior seems to be fine using the direct update via `entities/urn:ngsi-ld:Vehicle:A100/attrs/speed`:
```
curl --location --request POST 'http://localhost:9090/ngsi-ld/v1/entities' \
--header 'Content-Type: application/json' \
--header 'NGSILD-Tenant: openiot' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
        "id": "urn:ngsi-ld:Vehicle:A100",
        "type": "Vehicle",
        "brandName": {
            "type": "Property",
            "value": "Mercedes"
        },
        "speed": {
            "type": "Property",
            "value": 80
        }
    }'
```
But as soon as using the `entityOperations/upsert/` endpoint to update the entity (like the IoT agents do) the behavior again is broken as described above. (Once `entityOperations/upsert/` is used the update via `entities/urn:ngsi-ld:Vehicle:A100/attrs/speed` will also result in broken notification behavior)
