### ISSUE TITLE
Error 401 following the tutorial for the easy start

### ISSUE THREAD

**Issue by RoyBellingan** [ScorpioBroker/ScorpioBroker#571]
Following this page
https://scorpio.readthedocs.io/en/latest/API_walkthrough.html

after the start with (which btw is wrong as this command will print on screen, you should use wget or curl -O to write on disk)

```
curl https://raw.githubusercontent.com/ScorpioBroker/ScorpioBroker/development/docker-compose-aaio.yml
sudo docker-compose -f docker-compose-aaio.yml up
```

If I try to execute the suggested  (please note I added -v to print what is happening)

```
curl localhost:9090/ngsi-ld/v1/entities -v -s -S -H 'Content-Type: application/ld+json' -d @- <<EOF
        {
  "id": "house2:smartrooms:room1",
  "type": "Room",
  "temperature": {
        "value": 23,
        "unitCode": "CEL",
        "type": "Property",
        "providedBy": {
                "type": "Relationship",
                "object": "smartbuilding:house2:sensor0815"
         }
   },
  "isPartOf": {
        "type": "Relationship",
        "object": "smartcity:houses:house2"
  },
  "@context": [{"Room": "urn:mytypes:room", "temperature": "myuniqueuri:temperature", "isPartOf": "myuniqueuri:isPartOf"},"https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"]
}
EOF

I get

*   Trying 127.0.0.1:9090...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /ngsi-ld/v1/entities HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/ld+json
> Content-Length: 565
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< WWW-Authenticate: Bearer
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Tue, 25 Jun 2024 16:58:49 GMT
< 
* Connection #0 to host localhost left intact

```
HTTP 401 mean Unauthorized.

I tried to look around but I can not see how I can get identified, what should be a default username password (only one I could find in the config file are the one for the psg account)

Any idea how to debug ?

**Comment by RoyBellingan** [comment]
I was able to run using a different docker setup


```
version: '3'

services:
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    networks:
      - default_scorpio

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgres
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - default_scorpio

networks:
  default_scorpio:
    labels:
      org.fiware: 'etsi_ttf2_scorpio'
    ipam:
      config:
        - subnet: 172.18.1.0/24



```
