### ISSUE TITLE
How to build and run Scorpio

### ISSUE THREAD

**Issue by Manifesto24** [ScorpioBroker/ScorpioBroker#624]
Hi, 

I was trying to follow the documentation in order to build and run scorpio ( i want to run and experiment with the code overall)

So I followed those instructions:
https://scorpio.readthedocs.io/en/latest/buildScorpio.html

i can run without any problem `mvn clean package -DskipTests` and also `sudo mvn clean package -DskipTests -Pdocker-aaio`

However it is not clear which docker-compose to run after the compilation. And also im not sure if 1: where the built docker-compose is and 2: if the built docker-compose runs the code with the changes i have made.

I have also tried to keep postgresql in docker with all of the other containers and try run the docker microservices on the host but i had no luck:

```
`version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  atctxsrv:
    image: scorpiobroker/scorpio:AtContextServer_0.9.2-SNAPSHOT
    ports:
      - "27015:27015"
    depends_on:
      - kafka
      - eureka
  cfgsrv:
    image: scorpiobroker/scorpio:config-server_0.9.2-SNAPSHOT
    ports:
      - "8888:8888"
    depends_on:
      - eureka
  emgr:
    image: scorpiobroker/scorpio:EntityManager_0.9.2-SNAPSHOT
    ports:
      - "1025:1025"
    depends_on:
      - kafka
      - eureka
  eureka:
    image: scorpiobroker/scorpio:eureka-server_0.9.2-SNAPSHOT
    ports:
      - "8761:8761"
  gateway:
    image: scorpiobroker/scorpio:gateway_0.9.2-SNAPSHOT
    ports:
      - "9090:9090"
    depends_on:
      - eureka
`
```
and then run 
```
`java -jar Storage/StorageManager/target/StorageManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar Core/QueryManager/target/QueryManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar Registry/RegistryManager/target/RegistryManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar Core/EntityManager/target/EntityManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar History/HistoryManager/target/HistoryManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar Core/SubscriptionManager/target/SubscriptionManager-<VERSIONNUMBER>-SNAPSHOT.jar

java -jar Core/AtContextServer/target/AtContextServer-<VERSIONNUMBER>-SNAPSHOT.jar`
```

My goal is to make changes in the code build ideally a docker file and run the docker with my changes
